[package]
name = "my_blog"
version = "0.1.0"
edition = "2024"

[dependencies]
comrak = "0.50.0"
js-sys = "0.3.102"
leptos = { version = "0.8.16", features = ["csr"] }
leptos_router = "0.8.12"
markdown-frontmatter = "0.5.1"
serde = "1.0.228"




[lib]
name = "my_blog"
path = "src/lib.rs"

[[bin]]
name ="my_blog"
path = "src/bin/main.rs"
